version: '3.8'

services:
  postgres:
    image: postgres:17
    container_name: chatwithpdf_postgres
    restart: always
    environment:
      POSTGRES_USER: chatwithpdf_user
      POSTGRES_PASSWORD: chatwithpdf_pass
      POSTGRES_DB: chatwithpdf_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
